sudo: false
language: node_js
arch:
  - amd64
  - ppc64le
node_js:
  - '6'
  - '5'
  - '4'
  - '0.12'
  - '0.10'
matrix:
  fast_finish: true
  allow_failures:
    - node_js: '4'
    - node_js: '0.10'
    - node_js: '0.12'
